package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cartograph</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-d{border-color:var(--bg3);color:var(--cm)}.card{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.4rem;cursor:pointer;transition:.1s}.card:hover{background:var(--bg3)}.card h3{font-size:.8rem;margin-bottom:.15rem}.card-meta{font-size:.65rem;color:var(--cm)}.url-row{display:flex;align-items:center;gap:.5rem;padding:.3rem .5rem;border-bottom:1px solid var(--bg3);font-size:.72rem}.url-loc{flex:1;color:var(--rl)}.url-meta{font-size:.6rem;color:var(--cm)}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.form-row{display:flex;gap:.5rem}.form-row>*{flex:1}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Cartograph</span></h1><button class="btn btn-p" onclick="showNewSite()">+ Site</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/cartograph/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div id="siteList"></div><div id="detail" style="display:none;margin-top:1rem"></div></div><div id="modal"></div>
<script>
let sites=[],curSite='';
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function init(){const d=await api('/api/sites');sites=d.sites||[];
document.getElementById('siteList').innerHTML=sites.length?sites.map(s=>'<div class="card" onclick="openSite(\''+s.id+'\')"><h3>'+esc(s.name)+'</h3><div class="card-meta">'+esc(s.base_url)+' · '+s.url_count+' URLs</div></div>').join(''):'<div class="empty">No sites yet.</div>'}
async function openSite(id){curSite=id;const[s,ud]=await Promise.all([api('/api/sites/'+id),api('/api/sites/'+id+'/urls')]);
const urls=(ud.urls||[]).map(u=>'<div class="url-row"><span class="url-loc">'+esc(u.loc)+'</span><span class="url-meta">'+u.changefreq+' · p:'+u.priority+'</span><span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="delURL(\''+u.id+'\')">del</span></div>').join('');
document.getElementById('detail').style.display='block';
document.getElementById('detail').innerHTML='<div style="display:flex;justify-content:space-between;margin-bottom:.5rem"><span style="font-size:.75rem;color:var(--leather)">'+esc(s.name)+' ('+s.url_count+' URLs)</span><div style="display:flex;gap:.3rem"><button class="btn btn-p" onclick="addURL()">+ URL</button><a class="btn btn-p" href="/api/sites/'+id+'/sitemap.xml" target="_blank" style="text-decoration:none">sitemap.xml</a></div></div>'+(urls||'<div class="empty" style="padding:1rem">No URLs yet.</div>')}
async function delURL(id){await api('/api/urls/'+id,{method:'DELETE'});openSite(curSite);init()}
function showNewSite(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Site</h2><label class="fl">Name</label><input type="text" id="ns-name"><label class="fl">Base URL</label><input type="text" id="ns-url" placeholder="https://example.com"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="saveSite()">Create</button><button class="btn btn-d" onclick="closeModal()">Cancel</button></div></div></div>'}
async function saveSite(){const b={name:document.getElementById('ns-name').value,base_url:document.getElementById('ns-url').value};if(!b.name||!b.base_url){alert('Required');return};await api('/api/sites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();init()}
function addURL(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Add URL</h2><label class="fl">Path</label><input type="text" id="nu-loc" placeholder="/about"><div class="form-row"><div><label class="fl">Change Freq</label><select id="nu-freq"><option>always</option><option>hourly</option><option>daily</option><option selected>weekly</option><option>monthly</option><option>yearly</option><option>never</option></select></div><div><label class="fl">Priority</label><input type="text" id="nu-pri" value="0.5"></div></div><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="saveURL()">Add</button><button class="btn btn-d" onclick="closeModal()">Cancel</button></div></div></div>'}
async function saveURL(){const b={loc:document.getElementById('nu-loc').value,changefreq:document.getElementById('nu-freq').value,priority:document.getElementById('nu-pri').value};if(!b.loc){alert('Path required');return};await api('/api/sites/'+curSite+'/urls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();openSite(curSite);init()}
function closeModal(){document.getElementById('modal').innerHTML=''}
init()
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
